image: hashicorp/terraform:1.1.3

stages:
  - validate

before_script:
  - apk add curl gawk py3-pip bash perl build-base python3-dev libffi-dev
  - pip3 install --upgrade pip && pip3 install --upgrade setuptools
  - pip3 install wheel
  - pip3 install distlib --ignore-installed
  - pip3 install checkov
  - pip3 install pre-commit
  - curl -L "$(curl -s https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest | grep -o -E "https://.+?-linux-amd64" | head -n 1).tar.gz" > terraform-docs.tar.gz && tar -xvf terraform-docs.tar.gz && chmod +x terraform-docs && mv terraform-docs /usr/bin/
  - curl -L "$(curl -s https://api.github.com/repos/terraform-linters/tflint/releases/latest | grep -o -E "https://.+?_linux_amd64.zip")" > tflint.zip && unzip tflint.zip && rm tflint.zip && mv tflint /usr/bin/

# Rather than running individual validation commands, use pre-commit directly
validate:
  stage: validate
  script:
    - pre-commit run -a --show-diff-on-failure
  except:
    changes:
      - "README.md"
