repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform.git
    rev: v1.62.3
    hooks:
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_docs_without_aggregate_type_defaults
      - id: terraform_fmt
      - id: terraform_tflint
      - id: checkov
        args: ['--quiet', '--config-file', 'checkov-config.yaml']
